//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAI.Modules.HaiRegistrationMockup
{


    public partial class View
    {

        /// <summary>
        /// AccountLogin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HAI.Modules.HaiRegistrationMockup.UserControls.AccountLogin AccountLogin;

        /// <summary>
        /// ConfirmInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HAI.Modules.HaiRegistrationMockup.UserControls.ConfirmInfo ConfirmInfo;

        /// <summary>
        /// Personalnformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HAI.Modules.HaiRegistrationMockup.UserControls.Personalnformation Personalnformation;

        /// <summary>
        /// SelectMembership control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HAI.Modules.HaiRegistrationMockup.UserControls.SelectMembership SelectMembership;

        /// <summary>
        /// MembershipType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HAI.Modules.HaiRegistrationMockup.UserControls.MembershipType MembershipType;
    }
}
